# Generated by Django 3.2.9 on 2022-03-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cbid',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
